<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lenovo" failures="1" tests="3" name="Default test" time="37.885" errors="0" timestamp="2023-12-22T17:04:41 IST">
  <testcase classname="test.FaceBookLoginTest1" name="InvalidPasswordValidUsername" time="0.451"/>
  <testcase classname="test.FaceBookLoginTest1" name="InvalidPasswordInvalidUsername" time="1.01">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method test.FaceBookLoginTest1.InvalidPasswordInvalidUsername() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method test.FaceBookLoginTest1.InvalidPasswordInvalidUsername() didn't finish within the time-out 1000
at java.base@17.0.8/java.lang.Thread.sleep(Native Method)
at app//test.FaceBookLoginTest1.InvalidPasswordInvalidUsername(FaceBookLoginTest1.java:58)
at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.8/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- InvalidPasswordInvalidUsername -->
  <testcase classname="test.FaceBookLoginTest1" name="ValidPasswordInvalidUsername" time="0.316"/>
</testsuite> <!-- Default test -->
